general {
    lock_cmd = pidof hyprlock || hyprlock --config ~/.config/hypr/hyprlock.conf
    before_sleep_cmd = pidof hyprlock || hyprlock --config ~/.config/hypr/hyprlock.conf
    after_sleep_cmd = sleep 1 && hyprctl dispatch dpms on
}

listener {
    timeout = 300
    on-timeout = pidof hyprlock || hyprlock --config ~/.config/hypr/hyprlock.conf
}

listener {
    timeout = 600
    on-timeout = systemctl suspend
}
